# Generated by Django 5.2.2 on 2025-12-11 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('char_class', models.CharField(choices=[('tank', 'Tanque'), ('dps', 'DPS'), ('healer', 'Healer'), ('apprentice', 'Aprendiz')], max_length=16)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_atk', models.IntegerField(default=10)),
                ('base_def', models.IntegerField(default=5)),
                ('base_speed', models.IntegerField(default=1)),
                ('max_mana', models.IntegerField(default=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
