# Generated by Django 5.2.2 on 2025-12-14 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField(default=50)),
                ('base_atk', models.IntegerField(default=8)),
                ('base_def', models.IntegerField(default=3)),
                ('base_speed', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemies/')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='gems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AddField(
            model_name='character',
            name='lives',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='character',
            name='lives_last_tick',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='orbs_bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='orbs_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='orbs_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EnemySpawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='main_city', max_length=32)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('respawn_seconds', models.IntegerField(default=300)),
                ('is_alive', models.BooleanField(default=True)),
                ('next_respawn_at', models.DateTimeField(blank=True, null=True)),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemytype')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('rarity', models.CharField(choices=[('normal', 'Normal'), ('strong', 'Fuerte'), ('boss', 'Jefe'), ('legend', 'Leyenda')], max_length=20)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemytype')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slot', models.CharField(choices=[('helmet', 'Casco'), ('chest', 'Pechera'), ('pants', 'Pantalones'), ('boots', 'Botas'), ('main_hand', 'Mano Principal'), ('off_hand', 'Mano Secundaria'), ('amulet', 'Amuleto'), ('ring', 'Anillo'), ('pet', 'Mascota')], max_length=16)),
                ('rarity', models.CharField(choices=[('basic', 'Básica'), ('uncommon', 'Poco Común'), ('rare', 'Rara'), ('epic', 'Épica'), ('legendary', 'Legendaria'), ('mythic', 'Mítica'), ('ascended', 'Ascendida')], default='basic', max_length=16)),
                ('level', models.IntegerField(default=1)),
                ('base_hp', models.IntegerField(default=0)),
                ('base_atk', models.IntegerField(default=0)),
                ('base_def', models.IntegerField(default=0)),
                ('base_speed', models.IntegerField(default=0)),
                ('is_equipped', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=2)),
                ('y', models.IntegerField(default=7)),
                ('zone', models.CharField(default='main_city', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.character')),
            ],
        ),
    ]
